### ISSUE TITLE
Ability to pass HTMLElement as trigger selector

### ISSUE THREAD

**Issue by filipemerker** [diessica/password-revealer.js#2]
As far as I can see, to pass an `HTMLElement` as the `input` property is valid, but for `options.trigger.selector` you can only pass a class name or id. Why is that? 😬

**Comment by filipemerker** [comment]
Where is the web development ninja who is going to solve this problem for me?
I have the world famous HTMLElemnt and want to pass it as a parameter. Simple as that. I can send my code if you want.

**Comment by diessica** [comment]
HAHAHAHAHA!

Our JavaScript ninjas will be working on this feature request during this weekend.

Thank you!

**Comment by diessica** [comment]
Released on v1.1.0! :tada:
